// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDxiyfOE7GMdflazJCdmiF3DNYb7OAD7k',
    appId: '1:172818277486:web:ff5c1158df9fa762c7727f',
    messagingSenderId: '172818277486',
    projectId: 'chat-app-b44e9',
    authDomain: 'chat-app-b44e9.firebaseapp.com',
    databaseURL: 'https://chat-app-b44e9-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b44e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-noIVzXRRJRPn3U47LFalFN1d07thW88',
    appId: '1:172818277486:android:8ff5c8e06f453fe9c7727f',
    messagingSenderId: '172818277486',
    projectId: 'chat-app-b44e9',
    databaseURL: 'https://chat-app-b44e9-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b44e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52WJpNWSn8mBVjFWMhf66eeLzh_qNJxk',
    appId: '1:172818277486:ios:51b0b69d4f8aa744c7727f',
    messagingSenderId: '172818277486',
    projectId: 'chat-app-b44e9',
    databaseURL: 'https://chat-app-b44e9-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b44e9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD52WJpNWSn8mBVjFWMhf66eeLzh_qNJxk',
    appId: '1:172818277486:ios:51b0b69d4f8aa744c7727f',
    messagingSenderId: '172818277486',
    projectId: 'chat-app-b44e9',
    databaseURL: 'https://chat-app-b44e9-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b44e9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANSDKgfPl2BPE4x4oOH6V1cKToFZDf3W4',
    appId: '1:172818277486:web:9a5c17d684e1aa6bc7727f',
    messagingSenderId: '172818277486',
    projectId: 'chat-app-b44e9',
    authDomain: 'chat-app-b44e9.firebaseapp.com',
    databaseURL: 'https://chat-app-b44e9-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b44e9.appspot.com',
  );

}